### ISSUE TITLE
i've been getting error when creating new user

### ISSUE THREAD

**Issue by starascendin** [engageintellect/spatz-2#15]
<img width="603" alt="Screenshot 2024-09-15 at 7 52 37 PM" src="https://github.com/user-attachments/assets/50d764ce-3279-4f85-803a-2392328b8a11">

Got the above when creating new user

**Comment by engageintellect** [comment]
@starascendin ,

Were you trying to use an email address that you have used before? That's the only reason you should get this error (If I remember correctly).

I'll see if I can re-create your issue when I get a chance. Otherwise, feel free to submit a PR to make this page more robust/verbose. The associated code should be in /routes/auth/register/+error.svelte and /routes/auth/register/+page.server.ts

**Comment by starascendin** [comment]
I've tried w/ new emails (and manually creating user in pb), and got the same error.

I'll take a look at `/routes/auth/register/+page.server.ts`, and see what i find

**Comment by engageintellect** [comment]
Hmm, weird. I tried again and am unable to recreate on https://spatz2.engage-dev.com

Ahhh, I'm assuming this is in your dev env? If so, try to see if you can get the user you created manually to render on the client... just do something like this to your /routes/auth/register/+page.svelte

```
let data: any
import { currentUser } from `$lib/stores/user`;

$: currentUser.set(data.user)
console.log(data.user)
```

If your username is in the browser console output, everything should be connected. Otherwise, share whatever output you're getting in the browser and server consoles and I can try and help you debug.

**Comment by starascendin** [comment]
ah its my own fault, in the .env i left the comments there so pb didn't pick up the right url. That was what is causing the issue

**Comment by starascendin** [comment]
basically it was `PUBLIC_POCKETBASE_URL=http://localhost:8090/ (default should be something like localhost:8090)`

**Comment by starascendin** [comment]
i'll go ahead and close it, since this is a user error

**Comment by engageintellect** [comment]
> i'll go ahead and close it, since this is a user error

Right on, glad you got it sorted. Feel free to add any steps to the README I may have missed. I haven't actually done a proper run through to make sure the directions are 100%, so, any help or improvements are welcome.
