### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by bartonhammond** [engageintellect/spatz-2#16]
```masduende$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: spatz-2@0.2.6
npm ERR! Found: svelte@5.0.0-next.269
npm ERR! node_modules/svelte
npm ERR!   dev svelte@"^5.0.0-next.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@">4.0.0" from @iconify/svelte@4.0.2
npm ERR! node_modules/@iconify/svelte
npm ERR!   @iconify/svelte@"^4.0.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/bartonhammond/.npm/_logs/2024-10-18T16_51_28_266Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/bartonhammond/.npm/_logs/2024-10-18T16_51_28_266Z-debug-0.log
```

**Comment by engageintellect** [comment]
The error you're encountering stems from a conflict in dependency versions between `svelte@5.0.0-next.269` and `@iconify/svelte@4.0.2`. The `@iconify/svelte` package expects a peer dependency on `svelte` version `>4.0.0`, but the version of `svelte` you are using is from the 5.x beta or next release, which is causing the conflict.

Here are a few steps you can take to resolve this:

### Option 1: Use `--legacy-peer-deps`
This option tells npm to install the packages, ignoring peer dependency issues.

Run the following command:
```bash
npm install --legacy-peer-deps
```
This should bypass the peer dependency check and allow you to install the packages.

### Option 2: Force Installation
If you're okay with forcing the installation, you can use the `--force` flag, which installs the dependencies despite conflicts:

```bash
npm install --force
```
However, use this with caution as it may cause unexpected behavior.

### Option 3: Downgrade Svelte
Since `@iconify/svelte@4.0.2` expects a `svelte@4.x` version, you could downgrade to a stable Svelte 4.x version:

1. Edit your `package.json`:
   ```json
   "dependencies": {
     "svelte": "^4.0.0",
     "@iconify/svelte": "^4.0.2"
   }
   ```
2. Run:
   ```bash
   npm install
   ```

### Option 4: Use a Different Version of `@iconify/svelte`
You can check if there’s an update to `@iconify/svelte` that supports Svelte 5.x, or open an issue on the repository for them to add support for Svelte 5.

Let me know which option you'd prefer to try or if you need further help!

**Comment by engageintellect** [comment]
Having no issue installing dependencies from repo.


https://github.com/user-attachments/assets/15f3e56c-1a4f-4dfc-88ca-794aacacee93

Try deleting node_modules and .svelte-kit directories and installing again.
